name: Build and Deploy to GCS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Hugo
      run: wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.59.1/hugo_0.59.1_Linux-64bit.deb && sudo dpkg -i /tmp/hugo.deb
    - name: build
      run: hugo
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Upload files
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp -r public/* gs://developer20.com
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
